### ISSUE TITLE
How to read back the memory?

### ISSUE THREAD

**Issue by odbol** [cmaglie/Flash#1]
Hey this library looks really cool, however I have no idea how to use it. Can you add an example INO sketch that uses it? 

Specifically I want to figure out how to read back the values once I've written them. I see functions for writeData() but no readData()? Do I just use the `flash` address as a pointer to regular memory?

**Comment by cmaglie** [comment]
Hi Tyler,

I've updated the library and added an example, hope it helps.

BTW consider that:
- The API doesn't satisfy me, its not very Arduino like.
- Flash memory is erased every time you upload a new sketch in the board
- You have a limited number of writes in flash memory, so use them with parsimony!

have fun!
C
