### ISSUE TITLE
This project seems very interesting...but it seems abandoned. Is there any plans to relaunch it some day?

### ISSUE THREAD

**Issue by q2dg** [cmaglie/Flash#3]
...and extend it to Zero...
Thanks

**Comment by cmaglie** [comment]
Hi @q2dg!

This project is abandoned.

I've already made a similar library, called FlashStorage, for the Zero: https://github.com/cmaglie/FlashStorage
I've come up with a much better API, so my plan is to add support for the Due to FlashStorage and leave this one just as an archive.

**Comment by q2dg** [comment]
Ok! Thanks a lot!! 
I close the issue, then
